---
- name: NetArchitecture | Install and Configure
  hosts: all
  become: true

#  vars:
#    backup_ip_addr: "192.168.50.160"
#    client_ip_addr: "192.168.50.150"

  roles:
    - { role: netarchitecture, when: ansible_system == 'Linux' }
